src/Entity/CategorieSalle.php
<?php

namespace App\Entity;

use App\Repository\CategorieSalleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieSalleRepository::class)]
class CategorieSalle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $nom_categorie = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: Salle::class)]
    private Collection $salles;

    public function __construct()
    {
        $this->salles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Salle>
     */
    public function getSalles(): Collection
    {
        return $this->salles;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salles->contains($salle)) {
            $this->salles->add($salle);
            $salle->setCategorie($this);
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        if ($this->salles->removeElement($salle)) {
            // set the owning side to null (unless already changed)
            if ($salle->getCategorie() === $this) {
                $salle->setCategorie(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->nom_categorie;
    }
}

src/Form/CategorieSalleType.php
<?php

namespace App\Form;

use App\Entity\CategorieSalle;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CurrencyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieSalleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_categorie', TextType::class,[
                'required'=>true
            ])
            ->add('description', TextareaType::class, [
                'required'=>true
            ])
            ->add('prix', IntegerType::class,[
                'required'=>true
            ])
            ->add('Ajouter', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CategorieSalle::class,
        ]);
    }
}

src/Controller/CategorieSalleController.php
<?php

namespace App\Controller;

use App\Entity\CategorieSalle;
use App\Form\CategorieSalleType;
use App\Repository\CategorieSalleRepository;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function PHPUnit\Framework\equalTo;

#[Route('/categorieSalle'), IsGranted("IS_AUTHENTICATED_FULLY")]
class CategorieSalleController extends AbstractController
{
    #[Route('/voir/categorie/salle', name: 'app_categorie_salle'), IsGranted("ROLE_ADMIN")]
    public function index(
        Request $request,
        CategorieSalleRepository $categorieSalleRepository): Response
    {
        $categorieSalles= new CategorieSalle();
        $form=$this->createForm(CategorieSalleType::class,$categorieSalles);
        $form->remove('createdAt');
        $form->remove('updatedAt');
        $form->handleRequest($request);
        // je check dans la BDD si le nom que je récupère dans le formulaire existe dans la base ou pas si oui alors je pose une condition
        $checkSiNomCategorieExiste=$categorieSalleRepository->findBy(['nom_categorie'=>$form->get('nom_categorie')->getViewData()]);
        if($form->isSubmitted()&& $form->isValid())
        {
            if ($checkSiNomCategorieExiste!=null)
            {
                $this->addFlash('error','cette categorie existe déjà dans la base !');
            }else
            {
                $categorieSalles->setUpdatedAt(new \DateTimeImmutable());
                $categorieSalles->setCreatedAt(new \DateTimeImmutable());
                // la méthode add permet de persiter et de flush en même temps
                $categorieSalleRepository->add($categorieSalles, true);
                $this->addFlash('success','Enregistrement Réussi !');
            }
        }
        return $this->render('categorie_salle/index.html.twig', [
            'formCategorie' => $form->createView(),
            'categories'=>$categorieSalleRepository->findAll()
        ]);
    }
    #[Route('/supprimerCategory/{id}', name: 'supprimer.category')]
    public function supprimerCategory(CategorieSalleRepository $categorieSalleRepository,CategorieSalle $categorieSalle = null): Response
    {
        if ($categorieSalle) {
           $categorieSalleRepository->remove($categorieSalle,true);
            $this->addFlash('success', 'Suppression Réussi !');
        }
        else
        {
            $this->addFlash('error',"Opération Echoué !");
        }
        return $this->redirectToRoute('app_categorie_salle');
    }
    #[Route('/montrerSalle/{id}', name: 'montrer.category')]
    public function montrerCategorieSalle(CategorieSalle $categorieSalle=null): Response
    {
        return $this->render('categorie_salle/detailCategorie.html.twig', [
            'categorie' => $categorieSalle,
        ]);
    }
}

templates/categorie_salle/detailCategorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}categorie{% endblock %}

{% block body %}
    <h1>categorie</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nom De La Categorie</th>
            <th>Description</th>
            <th>Prix</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ categorie.id }}</td>
            <td>{{ categorie.nomCategorie }}</td>
            <td>{{ categorie.description }}</td>
            <td>{{ categorie.prix }} $</td>
            <td>
                <a href="{{ path('app_categorie_salle') }}" class="btn btn-tbl-arrow btn-xs">
                    <i class="fa fa-arrow-left"></i>
                </a>
                <a href="{#{{ path('', {'id': categorie.id}) }}#}" class="btn btn-tbl-edit btn-xs">
                    <i class="fa fa-pencil"></i>
                </a>
            </td>
        </tr>
        </tbody>
    </table>


    <a href="{{path('supprimer.category',{'id':categorie.id})}}">
        <button class="btn btn-tbl-delete btn-xs">
            <i class="fa fa-trash-o "></i>
        </button></a>
{%endblock%}

templates/categorie_salle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Categorie De Salle{% endblock %}

{% block body %}
    {% if is_granted('ROLE_ADMIN') %}
        {{form(formCategorie)}}
    {%endif%}
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card  card-box">
                <div class="card-head">
                    <header>Categories</header>
                    <div class="tools">
                        <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                        <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                        <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="table-wrap">
                        <div class="table-responsive">
                            <table class="table display product-overview mb-30" id="support_table5">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nom De La Categorie</th>
                                    <th>Description</th>
                                    <th>Prix</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%for categorie in categories %}
                                    <tr>
                                        <td>{{ categorie.id }}</td>
                                        <td>{{ categorie.nomCategorie }}</td>
                                        <td>{{ categorie.description }}</td>
                                        <td>{{ categorie.prix }} $</td>
                                        <td>
                                            <a href="{{path('montrer.category',{'id': categorie.id})}}" class="btn btn-tbl-info btn-xs">
                                                <i class="fa fa-info"></i>
                                            </a>
                                            {% if is_granted('ROLE_ADMIN') %}
                                            <a href="{#{{path('modifier.category',{'id':categorie.id})}}#}" class="btn btn-tbl-edit btn-xs">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="{{path('supprimer.category', {'id':categorie.id})}}">
                                            <button class="btn btn-tbl-delete btn-xs">
                                                <i class="fa fa-trash-o "></i>
                                            </button></a>
                                            {%endif%}
                                        </td>
                                    </tr>
                                {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}