src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToMany(targetEntity: Service::class, inversedBy: 'reservations')]
    private Collection $service;

    #[ORM\ManyToOne(inversedBy: 'reservation')]
    private ?Paiement $paiement = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_arriver = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 255)]
    private ?string $motif = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $user = null;

    public function __construct()
    {
        $this->service = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getService(): Collection
    {
        return $this->service;
    }

    public function addService(Service $service): self
    {
        if (!$this->service->contains($service)) {
            $this->service->add($service);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        $this->service->removeElement($service);

        return $this;
    }

    public function getPaiement(): ?Paiement
    {
        return $this->paiement;
    }

    public function setPaiement(?Paiement $paiement): self
    {
        $this->paiement = $paiement;

        return $this;
    }

    public function getDateArriver(): ?\DateTimeInterface
    {
        return $this->date_arriver;
    }

    public function setDateArriver(?\DateTimeInterface $date_arriver): self
    {
        $this->date_arriver = $date_arriver;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use App\Entity\Service;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_arriver',DateType::class,['required'=>true])
            ->add('date_fin',DateType::class, ['required'=>true])
            ->add('motif',TextareaType::class, ['required'=>true])
            ->add('service',EntityType::class,[
                'required'=>true,
                'multiple'=>true,
                'class'=>Service::class
            ])
//            ->add('paiement') rajouter code de paiement de type string
            ->add('user',EntityType::class, [
                'required'=>true,
                'class'=>Users::class
            ])
            ->add('Reserver',SubmitType::class)
        ;
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\RegionType;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
#[Route('/admin'),IsGranted("IS_AUTHENTICATED_FULLY")]
class ReservationController extends AbstractController
{
    #[Route('/reservation/{page?1}/{nbre?10}', name: 'app_reservation')]
    public function index($page,$nbre,Request $request, ReservationRepository $reservationRepository): Response
    {
        $reservation = new Reservation();
        $form=$this->createForm(ReservationType::class,$reservation);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $reservationRepository->add($reservation,true);// elle va persiter les elements recuperer dans le formulaire et flush dans la base
        }
        $nbReservation =$reservationRepository->count([]);
        return $this->render('reservation/index.html.twig', [
            'formReservation' => $form->createView(),
            'reservations'=>$reservationRepository->findBy([],[],$nbre,($page-1)*$nbre),
            'isPaginated'=>true,
            'nbrePage'=>ceil($nbReservation/$nbre),
            'page'=>$page,
            'nbre'=>$nbre
        ]);
    }
    #[Route('/montrerReservation/{id}', name: 'montrer.reservation')]
    public function montrerReservation(Reservation $reservation=null): Response
    {
        return $this->render('reservation/detailReservation.html.twig', [
            'reservation' => $reservation,
        ]);
    }
//    #[Route('/{id}/modifier', name: 'modifier.reservation', methods: ['GET', 'POST'])]
//    public function modifier(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
//    {
//        $form = $this->createForm(ReservationType::class, $reservation);
//        $form->handleRequest($request);
//
//        if ($form->isSubmitted() && $form->isValid()) {
//            $reservationRepository->add($reservation, true);
//
//            return $this->redirectToRoute('app_reservation');
//        }
//
////        return $this->renderForm('users/edit.html.twig', [
////            'reservation' => $reservation,
////            'form' => $form,
////        ]);
//        return new Response();
//    }
    #[Route('/supprimerReservation/{id}', name: 'supprimer.Reservation')]
    public function supprimerReservaiton(Reservation $reservation=null, ReservationRepository $reservationRepository): Response
    {
        if ($reservation) {
            $reservationRepository->remove($reservation, true);
            $this->addFlash('success','Suppression Réussi !');
        }else
        {
            $this->addFlash('error','Opération Echoué !');
        }
        return $this->redirectToRoute('app_reservation');
    }
}

templates/reservation/detailReservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}reservation{% endblock %}

{% block body %}
    <h1>reservation</h1>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Date Début Reservation</th>
            <th>Date Fin Reservation</th>
            <th>Motif</th>
            <th>Client</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ reservation.id }}</td>
            <td>{{ reservation.dateArriver|date("Y-M-D") }}</td>
            <td>{{ reservation.dateFin|date("Y-M-D") }}</td>
            <td>{{ reservation.motif }}</td>
            <td>{{ reservation.user}}</td>
            <td>
                <a href="{{ path('app_reservation') }}" class="btn btn-tbl-arrow btn-xs">
                    <i class="fa fa-arrow-left"></i>
                </a>
                <a href="{#{{ path('', {'id': reservation.id}) }}#}" class="btn btn-tbl-edit btn-xs">
                    <i class="fa fa-pencil"></i>
                </a>
            </td>
        </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{path('supprimer.Reservation',{'id':reservation.id})}}">
        <button class="btn btn-tbl-delete btn-xs">
            <i class="fa fa-trash-o "></i>
        </button></a>
    {%endif%}
{%endblock%}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
<div class="mb-3">
    {{form(formReservation)}}
</div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card  card-box">
                <div class="card-head">
                    <header>Reservation</header>
                    <div class="tools">
                        <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                        <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                        <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="table-wrap">
                        <div class="table-responsive">
                            <table class="table display product-overview mb-30" id="support_table5">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Date Début Reservation</th>
                                    <th>Date Fin Reservation</th>
                                    <th>Motif</th>
                                    <th>Client</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%for reservation in reservations %}
                                    <tr>
                                        <td>{{ reservation.id}}</td>
                                        <td>{{ reservation.dateArriver|date("Y-M-D")}}</td>
                                        <td>{{ reservation.dateFin|date("Y-M-D")}}</td>
                                        <td>{{ reservation.motif }}</td>
                                        <td>{{ reservation.user }}</td>
                                        <td>
                                            <a href="{{path('montrer.reservation',{'id':reservation.id})}}" class="btn btn-tbl-info btn-xs">
                                                <i class="fa fa-info"></i>
                                            </a>
                                            <a href="{#{{path('modifier.reservation',{'id':reservation.id})}}#}" class="btn btn-tbl-edit btn-xs">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="{{path('supprimer.Reservation',{'id':reservation.id})}}">
                                                <button class="btn btn-tbl-delete btn-xs">
                                                    <i class="fa fa-trash-o "></i>
                                                </button>
                                            </a>
                                        </td>
                                    </tr>
                                {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if isPaginated is defined and isPaginated %}
        <div class="row mt-2">
            <nav aria-label="col Page navigation example">
                <ul class="pagination">
                    {% if page != 1 %}
                        <li class="page-item">
                            <a
                                    class="page-link"
                                    href="{{ path('app_reservation', {page: page - 1, nbre: nbre}) }}"
                            >
                                Previous
                            </a></li>
                    {% endif %}
                    {% for i in range(1, nbrePage) %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ path('app_reservation', {page: i, nbre: nbre}) }}"
                            >{{ i }}
                            </a>
                        </li>
                    {% endfor %}
                    {% if page != nbrePage %}
                        <li class="page-item">
                            <a
                                    class="page-link"
                                    href="{{ path('app_reservation', {page: page + 1, nbre: nbre}) }}"
                            >Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    {% endif %}
{% endblock %}