src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VilleRepository::class)]
class Ville
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom_ville = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'villes')]
    private ?Province $Province = null;

    #[ORM\ManyToOne(inversedBy: 'villes')]
    private ?Region $region = null;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomVille(): ?string
    {
        return $this->nom_ville;
    }

    public function setNomVille(string $nom_ville): self
    {
        $this->nom_ville = $nom_ville;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getProvince(): ?Province
    {
        return $this->Province;
    }

    public function setProvince(?Province $Province): self
    {
        $this->Province = $Province;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }
    public function __toString() {
        return $this->nom_ville;
    }
}

src/Form/VilleType.php
<?php

namespace App\Form;

use App\Entity\Province;
use App\Entity\Region;
use App\Entity\Ville;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VilleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_ville', TextType::class, ['required'=>true])
            ->add('Province', EntityType::class, [
                'required'=>true,
                'class'=> Province::class
            ])
            ->add('region', EntityType::class,[
                'required'=>true,
                'class'=>Region::class
            ])
            ->add('Ajouter', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ville::class,
        ]);
    }
}

src/Controller/VilleController.php
<?php

namespace App\Controller;

use App\Entity\Role;
use App\Entity\Ville;
use App\Form\VilleType;
use App\Repository\VilleRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\Translation\t;

#[Route('/ville'),IsGranted("IS_AUTHENTICATED_FULLY")]
class VilleController extends AbstractController
{
    #[Route('/voiretajouter/{page?1}/{nbre?10}', name: 'app_ville')]
    public function index($page,$nbre, Request $request, VilleRepository $villeRepository): Response
    {
        $villes = new Ville();
        $form=$this->createForm(VilleType::class,$villes);
        $form->remove('createdAt');
        $form->remove('updatedAt');
        $form->handleRequest($request);
        // je check dans la BDD si le nom que je récupère dans le formulaire existe dans la base ou pas si oui alors je pose une condition
        $findIfVilleExist=$villeRepository->findBy(['nom_ville'=>$form->get('nom_ville')->getViewData()]);
        if ($form->isSubmitted() && $form->isValid())
        {
            if ($findIfVilleExist!=null)
            {
                $this->addFlash('error', 'cette ville est déjà ');
            }
            else
            {
                $villes->setUpdatedAt(new \DateTimeImmutable());
                $villes->setCreatedAt(new \DateTimeImmutable());
                $villeRepository->add($villes,true);// la méthode add permet de persiter et de flush en même temps
                $this->addFlash('success','Enregistrement réussi!');
            }
        }
        $nbrVille=$villeRepository->count([]);
        return $this->render('ville/Ville.html.twig', [
            'formVille' => $form->createView(),
            'Villes'=>$villeRepository->findBy([],[],$nbre,($page-1)*$nbre),
            'isPaginated'=>true,
            'nbrePage'=>ceil($nbrVille/$nbre),
            'page'=>$page,
            'nbre'=>$nbre
        ]);
    }
    #[Route('/supprimerVille/{id}', name: 'supprimer.ville')]
    public function supprimerVille(VilleRepository $villeRepository, Ville $ville = null): Response
    {
        $form=$this->createForm(VilleType::class,$ville);
        if ($ville) {
           $villeRepository->remove($ville,true);
            $this->addFlash('success', 'Suppression Réussi !');
        }
        else {$this->addFlash('error',"cette ville n'existe pas dans la base !");}
        return $this->redirectToRoute('app_ville');
    }
    #[Route('/montrerVille/{id}', name: 'montrer.ville')]
    public function montrerVille(Ville $ville=null): Response
    {
        return $this->render('ville/voirVille.html.twig', [
            'ville' => $ville,
        ]);
    }
}

templates/ville/Ville.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ville{% endblock %}

{% block body %}
    {% if is_granted('ROLE_ADMIN') %}
    <div class="mb-3">
            {{form(formVille)}}

    </div>
    {%endif%}
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card  card-box">
                <div class="card-head">
                    <header>Ville</header>
                    <div class="tools">
                        <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                        <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                        <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="table-wrap">
                        <div class="table-scrollable">
                            <table class="table table-hover table-checkable order-column full-width"
                                   id="example4">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nom De La Ville</th>
                                    <th>Region</th>
                                    <th>Province</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%for ville in Villes %}
                                    <tr {#class="odd gradeX"#}>
                                        <td class="center">{{ ville.id }}</td>
                                        <td >{{ ville.nomVille }}</td>
                                        <td>{{ ville.region }}</td>
                                        <td>{{ ville.province }}</td>
                                        <td>
                                            <a href="{{path('montrer.ville',{'id':ville.id})}}" class="btn btn-tbl-info btn-xs">
                                                <i class="fa fa-info"></i>
                                            </a>
                                            {% if is_granted('ROLE_ADMIN') %}
                                                <a href="{#{{path('modifier.ville', {'id':ville.id})}}#}" class="btn btn-tbl-edit btn-xs">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                            <a href="{{path('supprimer.ville',{'id':ville.id})}}">
                                            <button class="btn btn-tbl-delete btn-xs">
                                                    <i class="fa fa-trash-o "></i>
                                                </button></a>
                                            {%endif%}
                                        </td>
                                    </tr>
                                {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if isPaginated is defined and isPaginated %}
        <div class="row mt-2">
            <nav aria-label="col Page navigation example">
                <ul class="pagination">
                    {% if page != 1 %}
                        <li class="page-item">
                            <a
                                    class="page-link"
                                    href="{{ path('app_privillege', {page: page - 1, nbre: nbre}) }}"
                            >
                                Previous
                            </a></li>
                    {% endif %}
                    {% for i in range(1, nbrePage) %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ path('app_ville', {page: i, nbre: nbre}) }}"
                            >{{ i }}
                            </a>
                        </li>
                    {% endfor %}
                    {% if page != nbrePage %}
                        <li class="page-item">
                            <a
                                    class="page-link"
                                    href="{{ path('app_ville', {page: page + 1, nbre: nbre}) }}"
                            >Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    {% endif %}
{% endblock %}

templates/ville/voirVille.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ville{% endblock %}

{% block body %}
<h1>Ville</h1>
<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Nom De La Ville</th>
        <th>Region</th>
        <th>Province</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ ville.id }}</td>
        <td>{{ ville.nomVille }}</td>
        <td>{{ ville.region }}</td>
        <td>{{ ville.province }}</td>
        <td>
            <a href="{{ path('app_ville') }}" class="btn btn-tbl-arrow btn-xs">
                <i class="fa fa-arrow-left"></i>
            </a>
            {% if is_granted('ROLE_ADMIN') %}
            <a href="{#{{ path('', {'id': ville.id}) }}#}" class="btn btn-tbl-edit btn-xs">
                <i class="fa fa-pencil"></i>
            </a>
            {%endif%}
        </td>
    </tr>
    </tbody>
</table>

    {% if is_granted('ROLE_ADMIN') %}
<a href="{{path('supprimer.ville',{'id':ville.id})}}">
    <button class="btn btn-tbl-delete btn-xs">
        <i class="fa fa-trash-o "></i>
    </button></a>
    {%endif%}
{%endblock%}