src/Entity/Region.php
<?php

namespace App\Entity;

use App\Repository\RegionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RegionRepository::class)]
class Region
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom_region = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'region', targetEntity: Province::class)]
    private Collection $provinces;

    #[ORM\OneToMany(mappedBy: 'region', targetEntity: Ville::class)]
    private Collection $villes;

    public function __construct()
    {
        $this->provinces = new ArrayCollection();
        $this->villes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomRegion(): ?string
    {
        return $this->nom_region;
    }

    public function setNomRegion(string $nom_region): self
    {
        $this->nom_region = $nom_region;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Province>
     */
    public function getProvinces(): Collection
    {
        return $this->provinces;
    }

    public function addProvince(Province $province): self
    {
        if (!$this->provinces->contains($province)) {
            $this->provinces->add($province);
            $province->setRegion($this);
        }

        return $this;
    }

    public function removeProvince(Province $province): self
    {
        if ($this->provinces->removeElement($province)) {
            // set the owning side to null (unless already changed)
            if ($province->getRegion() === $this) {
                $province->setRegion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ville>
     */
    public function getVilles(): Collection
    {
        return $this->villes;
    }

    public function addVille(Ville $ville): self
    {
        if (!$this->villes->contains($ville)) {
            $this->villes->add($ville);
            $ville->setRegion($this);
        }

        return $this;
    }

    public function removeVille(Ville $ville): self
    {
        if ($this->villes->removeElement($ville)) {
            // set the owning side to null (unless already changed)
            if ($ville->getRegion() === $this) {
                $ville->setRegion(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->nom_region;
    }
}

src/Form/RegionType.php
<?php

namespace App\Form;

use App\Entity\Region;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_region')
            ->add('Ajouter', SubmitType::class) ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Region::class,
        ]);
    }
}

src/Controller/RegionController.php
<?php

namespace App\Controller;

use App\Entity\Region;
use App\Form\RegionType;
use App\Repository\RegionRepository;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
#[Route('/region'),IsGranted('IS_AUTHENTICATED_FULLY')]
class RegionController extends AbstractController
{
    #[Route('/liste/{page?1}/{nbre?10}', name: 'app_region'),IsGranted("ROLE_ADMIN")]
    public function index($page,$nbre,Request $request, RegionRepository $regionRepository): Response
    {
        $region = new Region();
        $form=$this->createForm(RegionType::class,$region);
        $form->handleRequest($request);
        // je check dans la BDD si le nom que je récupère dans le formulaire existe dans la base ou pas si oui alors je pose une condition
        $findregionNom=$regionRepository->findBy(['nom_region'=>$form->get('nom_region')->getViewData()]);
        if ($form->isSubmitted() && $form->isValid())
        {
            if($findregionNom!=null)
            {
             $this->addFlash('error','cette region existe déjà !');
            }
            else
            {
                $region->setCreatedAt(new \DateTimeImmutable());
                $region->setUpdatedAt(new  \DateTimeImmutable());
                $regionRepository->add($region,true);// la méthode add permet de persiter et de flush en même temps
                $this->addFlash('success','Enregistrement reussi!');
            }
        }
        $nbRegion =$regionRepository->count([]);
        return $this->render('region/region.html.twig', [
            'formRegion' => $form->createView(),
            'regions'=>$regionRepository->findBy([],[],$nbre,($page-1)*$nbre),
            'isPaginated'=>true,
            'nbrePage'=>ceil($nbRegion/$nbre),
            'page'=>$page,
            'nbre'=>$nbre
        ]);
    }
    #[Route('/supprimerRegion/{id}', name: 'supprimer.region')]
    public function supprimerRegion(Region $region = null,RegionRepository $regionRepository): Response
    {
        if ($region) {
            $regionRepository->remove($region, true);
            $this->addFlash('success', 'Suppression Réussi !');
        }
        else
        {
            $this->addFlash('error',"Opération Echoué !");
        }
        return $this->redirectToRoute('app_region');
    }
    #[Route('/montrerRegion/{id}', name: 'montrer.region')]
    public function montrerRegion(Region $region=null): Response
    {
        return $this->render('region/detailRegion.html.twig', [
            'region' => $region,
        ]);
    }
}

templates/region/detailRegion.html.twig
{% extends 'base.html.twig' %}

{% block title %}region{% endblock %}

{% block body %}
    <h1>region</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nom De La Region</th>
           
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ region.id }}</td>
            <td>{{ region.nomregion }}</td>
            <td>
                <a href="{{ path('app_region') }}" class="btn btn-tbl-arrow btn-xs">
                    <i class="fa fa-arrow-left"></i>
                </a>
                <a href="{#{{ path('', {'id': region.id}) }}#}" class="btn btn-tbl-edit btn-xs">
                    <i class="fa fa-pencil"></i>
                </a>
            </td>
        </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{path('supprimer.region',{'id':region.id})}}">
        <button class="btn btn-tbl-delete btn-xs">
            <i class="fa fa-trash-o "></i>
        </button></a>
    {%endif%}
{%endblock%}

templates/region/region.html.twig
{% extends 'base.html.twig' %}

{% block title %}Region{% endblock %}

{% block body %}
    {% if is_granted('ROLE_ADMIN') %}
    <div class="mb-3">
            {{form(formRegion)}}
    </div>
    {%endif%}
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card  card-box">
                <div class="card-head">
                    <header>Region</header>
                    <div class="tools">
                        <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                        <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                        <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="table-wrap">
                        <div class="table-responsive">
                            <table class="table display product-overview mb-30" id="support_table5">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nom De la Region</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%for region in regions %}
                                    <tr>
                                        <td>{{ region.id }}</td>
                                        <td>{{ region.nomRegion }}</td>
                                        <td>
                                            <a href="{{path('montrer.region',{'id':region.id})}}" class="btn btn-tbl-info btn-xs">
                                                <i class="fa fa-info"></i>
                                            </a>
                                            {% if is_granted('ROLE_ADMIN') %}
                                            <a href="{#{{path('modifier.region',{'id':region.id})}}#}" class="btn btn-tbl-edit btn-xs">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="{{path('supprimer.region',{'id':region.id})}}">
                                            <button class="btn btn-tbl-delete btn-xs">
                                                <i class="fa fa-trash-o "></i>
                                            </button></a>
                                            {%endif%}
                                        </td>
                                    </tr>
                                {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if isPaginated is defined and isPaginated %}
        <div class="row mt-2">
            <nav aria-label="col Page navigation example">
                <ul class="pagination">
                    {% if page != 1 %}
                        <li class="page-item">
                            <a
                                    class="page-link"
                                    href="{{ path('app_region', {page: page - 1, nbre: nbre}) }}"
                            >
                                Previous
                            </a></li>
                    {% endif %}
                    {% for i in range(1, nbrePage) %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ path('app_region', {page: i, nbre: nbre}) }}"
                            >{{ i }}
                            </a>
                        </li>
                    {% endfor %}
                    {% if page != nbrePage %}
                        <li class="page-item">
                            <a
                                    class="page-link"
                                    href="{{ path('app_region', {page: page + 1, nbre: nbre}) }}"
                            >Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>

        </div>
    {% endif %}
{% endblock %}